import localFont from "next/font/local";
import "./globals.css";
import MainSidebar from "./components/MainSidebar";
import Header from "./components/Header";
import StoreProvider from "./StoreProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StoreProvider>
        <main className="w-full h-[100dvh] flex flex-col-reverse lg:flex-row">
          {/* sidebar */}
          <div>
            <MainSidebar />
          </div>
          <aside className="w-full h-[calc(100dvh-50px)]  overflow-none">
          <header>
            <Header />
          </header>
            <section className="w-full h-[calc(100dvh-100px)] md:h-full overflow-auto">{children}</section>
          </aside>
        </main>
        </StoreProvider>
        
      </body>
    </html>
  );
}
